// WIT design guidelines https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md
// https://component-model.bytecodealliance.org/design/wit.html
package spin:mqtt-trigger-sdk;

world spin-mqtt {
  /// General purpose error.
    enum error {
      success,
      error,
  }

  /// MQTT QoS levels.
  enum qos {
      at-most-once,
      at-least-once,
      exactly-once,
  }

  /// The message payload.
  type payload = list<u8>;

  /// The entrypoint for a Mqtt handler in wasm component  
  export handle-message: func(message: payload);
}